feat(toast): add stubbed swipeGesture (#28380)
Issue number: N/A

---------

<!-- Please do not submit updates to dependencies unless it fixes an
issue. -->

<!-- Please try to limit your pull request to one type (bugfix, feature,
etc). Submit multiple pull requests if needed. -->

## What is the current behavior?
<!-- Please describe the current behavior that you are modifying. -->

Toast does not support swipe gestures to dismiss.

## What is the new behavior?
<!-- Please describe the behavior or changes that are being added by
this PR. -->

- Adds a `swipeGesture` property to enable this behavior
- Creates an HTML playground so I can later write E2E tests
- Adds stubbed implementations for creating and destroying the swipe
gesture on prop change, present, and dismiss
- Adds unit tests to verify that the gesture is being created/destroyed
on prop change, present, and dismiss

In
https://github.com/ionic-team/ionic-framework/pull/28380/commits/cf7e8976a76ca338123abf3ddd6a3863c956f7db
I moved the toast config tests to separate file. For some reason this
was causing issues with my new tests. This might be a Stencil bug given
that I got the following error:

```js
, getValue = (e, t) => getHostRef(e).$instanceValues$.get(t), setValue = (e, t, a, o) => {
                                     ^

TypeError: Cannot read properties of undefined (reading '$instanceValues$')
    at getValue (/Users/liamdebeasi/Ionic/ionic/core/node_modules/@stencil/core/internal/testing/index.js:508:38)
    at Toast.get [as position] (/Users/liamdebeasi/Ionic/ionic/core/node_modules/@stencil/core/internal/testing/index.js:538:13)
    at Toast.dismiss (/Users/liamdebeasi/Ionic/ionic/core/src/components/toast/toast.tsx:208:30)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:533:9)
    at processTimers (node:internal/timers:507:7)
```

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

<!-- If this introduces a breaking change, please describe the impact
and migration path for existing applications below. -->


## Other information

<!-- Any other information that is important to this PR such as
screenshots of how the component looks before and after the change. -->

Note: This PR is missing some build artifacts. I will add those once
https://github.com/ionic-team/ionic-framework/pull/28379 is merged and
synced into this branch.