Updated Vue example to clear typescript errors.
Without the changes, `vue-cli-service` will report the following problems:

ERROR in src/views/Tab1Page.vue:67:26
TS2345: Argument of type 'number' is not assignable to parameter of type 'never'.
    65 |       const min = max - 20;
    66 |       for (let i = min; i < max; i++) {
  > 67 |         items.value.push(i);
       |                          ^
    68 |       }
    69 |     }
    70 |     
ERROR in src/views/Tab1Page.vue:75:9
TS2531: Object is possibly 'null'.
    73 |         pushData();
    74 |         console.log('Loaded data');
  > 75 |         ev.target.complete();
       |         ^^^^^^^^^
    76 |   
    77 |         // App logic to determine if all data is loaded
    78 |         // and disable the infinite scroll
ERROR in src/views/Tab1Page.vue:75:19
TS2339: Property 'complete' does not exist on type 'EventTarget'.
    73 |         pushData();
    74 |         console.log('Loaded data');
  > 75 |         ev.target.complete();
       |                   ^^^^^^^^
    76 |   
    77 |         // App logic to determine if all data is loaded
    78 |         // and disable the infinite scroll
ERROR in src/views/Tab1Page.vue:80:11
TS2531: Object is possibly 'null'.
    78 |         // and disable the infinite scroll
    79 |         if (items.value.length == 1000) {
  > 80 |           ev.target.disabled = true;
       |           ^^^^^^^^^
    81 |         }
    82 |       }, 500);
    83 |     }
ERROR in src/views/Tab1Page.vue:80:21
TS2339: Property 'disabled' does not exist on type 'EventTarget'.
    78 |         // and disable the infinite scroll
    79 |         if (items.value.length == 1000) {
  > 80 |           ev.target.disabled = true;
       |                     ^^^^^^^^
    81 |         }
    82 |       },